language:
  ruby

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rspec
  - bundle exec rubocop

after_script:
  - bundle exec rake coveralls:push

install:
  - if [ $TRAVIS_RUBY_VERSION == '2.2' || $TRAVIS_RUBY_VERSION == '2.1' || $TRAVIS_RUBY_VERSION == '2.0']; then
      echo $TRAVIS_RUBY_VERSION
      gem install bundler -v '~> 1.6'
    else
      gem install bundler
    fi
  - gem install rainbow -v '2.2.1'
  - bundle install
